---

- name: recover backup
  synchronize:
    src: "{{ billy_home }}/backup_ui/ui"
    dest: "{{ billy_home }}"
  delegate_to: "{{ inventory_hostname }}"
  listen: "ui handler"
  when: ui_handler_guard == "start"
  become: true

- name: delete backup
  file:
    state: absent
    path: "{{ billy_home }}/backup_ui"
  listen: "ui handler"
  become: true
  
- name: fail message
  debug:
    msg:
    - "An error occured during the upgrade of role {{ role_name }}"
    - "Please restart the server {{ inventory_hostname }}"
    - "Try to upgrade {{ product_name }} later or contact the support support@cactus.de"
  listen: "ui handler"
  when: ui_handler_guard == "start"
