---
# for installation options see https://github.com/CactuseSecurity/billy/blob/master/documentation/installer/install-advanced.md

- hosts: all
  tasks:
    - name: uninstall product
      import_tasks: scripts/uninstall-billy.yml
      when: "installation_mode == 'uninstall'"
      become: true
  tags:
    - backend
    - frontend

- hosts: all
  roles:
    - { role: common, when: "not installation_mode == 'uninstall'" }
  tags:
    - backend
    - api
    - ui
    - frontend

- hosts: databaseserver
  roles:
    - { role: database, when: "not installation_mode == 'uninstall'" }
  tags:
    - backend

- hosts: middlewareserver
  roles:
    - { role: openldap-server, when: "not installation_mode == 'uninstall'" }
    - { role: lib, when: "not installation_mode == 'uninstall'" }
    - { role: middleware, when: "not installation_mode == 'uninstall'" }
  tags:
    - backend
    - csharp

- hosts: apiserver
  roles:
    - { role: docker, when: "not installation_mode == 'uninstall'" }
  tags:
    - backend
    - api

# do not put this into the same play as docker (handler needs to run inbetween!)
- hosts: apiserver 
  roles:
    - { role: api, when: "not installation_mode == 'uninstall'" }
  tags:
    - backend
    - api

- hosts: frontends
  roles:
    - { role: lib, when: "not installation_mode == 'uninstall'"}
    - { role: ui, when: "not installation_mode == 'uninstall'"}
  tags:
    - frontend
    - csharp
    - ui

- hosts: frontends
  tasks:
    - name: restart ui service to display new version
      service:
        name: "{{ ui_service_name }}"
        state: restarted
      become: true
      when: "not installation_mode == 'uninstall'"
  tags:
    - frontend
    - ui

- hosts: all
  roles:
    - { role: test, when: "not installation_mode == 'uninstall'" }
  tags:
    - test

- hosts: all
  roles:
    - { role: cleanup, when: "not installation_mode == 'uninstall'" }
  tags:
    - cleanup
    - backend
    - frontend
    - ui

- hosts: all
  roles:
    - { role: final-display, when: "not installation_mode == 'uninstall'" }
  tags:
    - cleanup
    - backend
    - frontend
    - ui
