# 1. ssh-keygen -t rsa
# Press enter for each line 
# 2. cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
# 3. chmod og-wx ~/.ssh/authorized_keys
# 4. change ansible_connection to ssh and ansible_host to your host

all:
  hosts:
    install-srv:
      ansible_connection: local
      ansible_host: localhost
#   Add servers for distributed installation here. Use these servers in the children dictionary below.
#    ui-srv:
#      ansible_connection: ssh
#      ansible_host: 192.168.121.2
  children:
    frontends:
      hosts:
        install-srv:
    backendserver:
      hosts:
        install-srv:
    databaseserver:
      hosts:
        install-srv:
    apiserver:
      hosts:
        install-srv:
    importers:
      hosts:
        install-srv:
    middlewareserver:
      hosts:
        install-srv:
    sampleserver:
      hosts:
        install-srv:
    testservers:
      hosts:
        install-srv:
    logserver:
      hosts:
        install-srv:
