# 1. ssh-keygen -t rsa
# Press enter for each line 
# 2. cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
# 3. chmod og-wx ~/.ssh/authorized_keys
# 4. change ansible_connection to ssh and ansible_host to your host

all:
  hosts:
    localhost:
      ip_address: 127.0.0.1
      ansible_connection: local
  children:

    frontends:
      hosts:
        localhost:

    # only one databaseserver should exist
    databaseserver:
      hosts:
        localhost:

    # only one apiserver should exist
    apiserver:
      hosts:
        localhost:

    # only one middlewareserver should exist
    middlewareserver:
      hosts:
        localhost:

    # only one sampleserver should exist
    sampleserver:
      hosts:
        localhost:

    testservers:
      hosts:
        localhost:

    # only one logserver should exist
    logserver:
      hosts:
        localhost:
