- name: Reload service systemctl
  systemd:
    daemon_reload: yes
  listen: "restart daemons"
  become: yes

- name: restart webhook service 
  service:
    name: fworch-webhook-receiver
    state: restarted       
  listen: "restart daemons"
  become: yes
