
- block:
    - name: initialize handler for datarecovery
      set_fact:
        ui_handler_guard: start
      changed_when: true
      notify:
      - ui handler
      when: installation_mode == "upgrade"

    - name: check for ui dir
      stat:
        path: "{{ billy_home }}/ui"
      register: ui_dir_check

    - name: backup ui dir
      synchronize:
        src: "{{ billy_home }}/ui"
        dest: "{{ billy_home }}/backup_ui"
      delegate_to: "{{ inventory_hostname }}"
      when: ui_dir_check.stat.exists and installation_mode == "upgrade"

    - name: remove ui dir
      file:
        state: absent
        path: "{{ billy_home }}/ui"
      when: installation_mode == "upgrade"

    - name: create ui dir
      file:
        dest: "{{ ui_dir }}"
        state: directory
        owner: "{{ billy_user }}"
        group: "{{ billy_group }}"

    - name: copy ui files to frontend target
      copy:
        src: "{{ item }}"
        dest: "{{ ui_dir }}"
        owner: "{{ billy_user }}"
        group: "{{ billy_group }}"
      loop:
        - billy.UI
      tags: [ 'test' ]

  become: true

- include_tasks: ui_apache_install_and_setup.yml

- include_tasks: install_and_run_ui_service.yml

- name: include upgrade script
  import_tasks: run-upgrades.yml
  when: "installation_mode == 'upgrade'"

- name: finalize handler for datarecovery
  set_fact:
    ui_handler_guard: stop
  changed_when: true
  notify: "ui handler"
  when: installation_mode == "upgrade"
