# add db users and assign groups

- block:

  - name: create db groups
    postgresql_user:
      name: "{{ item }}"
    loop: "{{ database_groups }}"
       
  - name: create db users
    postgresql_user:
      name: "{{ item }}"
      role_attr_flags: LOGIN,NOSUPERUSER,INHERIT,NOCREATEDB,NOCREATEROLE
    loop: "{{ database_users }}"

  - name: add user dbbackup to group dbbackupusers
    postgresql_query:
      db: "{{ billy_db_name }}"
      query: GRANT dbbackupusers TO dbbackup

  # - name: add user billy to group billyadmins
  #   postgresql_query:
  #     db: "{{ billy_db_name }}"
  #     query: GRANT billyadmins TO billy

  become: true
  become_user: postgres
