- name: make sure {{ billy_home }}/etc/secrets exists
  file:
    path: "{{ billy_home }}/etc/secrets"
    state: directory
    owner: "{{ billy_user }}"
    group: "{{ billy_group }}"
    mode: "0700"
  become: true

- name: set dbadmin password from parameter
  set_fact:
    dbadmin_password: "{{ dbadmin_initial_password }}"
  when: dbadmin_initial_password is defined

- name: set dbadmin password randomly
  set_fact:
    dbadmin_password: "{{ randomly_generated_pwd }}"
  when: dbadmin_initial_password is not defined

- name: write dbadmin_password password to secret directory
  copy:
    content: "{{ dbadmin_password }}\n"
    dest: "{{ dbadmin_password_file }}"
    mode: '0600'
    owner: "{{ billy_user }}"
    group: "{{ billy_group }}"
  become: true

- name: set billy db password randomly
  set_fact:
    billy_db_password: "{{ randomly_generated_pwd }}"

- name: write billy_db_password to secrets directory
  copy:
    content: "{{ billy_db_password }}\n"
    dest: "{{ billy_db_password_file }}"
    mode: '0600'
    owner: "{{ billy_user }}"
    group: "{{ billy_group }}"
  become: true

- block:

  - name: fail upon new installation with existing database
    fail:
      msg: "Error: You chose new installation on a system with existing database {{ billy_db_name }}"
    when: installation_mode == "new" and db_exists.query_result.0.count != 0

  - name: create postgres user "{{ billy_dbadmin_name }}"
    postgresql_user: 
      name: "{{ billy_dbadmin_name }}"
      password: "{{ dbadmin_password }}"
      encrypted: true
      role_attr_flags: CREATEDB,SUPERUSER,CREATEROLE,INHERIT,LOGIN

  - name: create postgres user "{{ billy_user }}"
    postgresql_user: 
      name: "{{ billy_user }}"
      password: "{{ billy_db_password }}"
      encrypted: true
      role_attr_flags: LOGIN

  # include add-tablespace.yml here

  - name: create database {{ billy_db_name }}
    postgresql_db:
      name: "{{ billy_db_name }}"
      state: present

  - name: test module postgresql_query functionality (only works with ansible >= 2.8) in case of an error message you may run scripts/install-lastes-ansible.yml
    postgresql_query:
      db: "{{ billy_db_name }}"
      query: 'select version()'
    register: test_query
    when: ansible_version.full is version ('2.10', '>=')

  - name: show dummy query result
    debug:
      msg: "test_query result: {{ test_query }}"

  - name: include table creation
    include_tasks: install-db-base.yml
    
  - name: create db users with group memberships
    import_tasks: create-users.yml
    when: installation_mode == "new"

  become: true
  become_user: postgres
