
- block:

  - name: creating {{ billy_db_name }}-db-model
    community.postgresql.postgresql_query:
      db: "{{ billy_db_name }}"
      path_to_script: "{{ database_install_dir }}/sql/creation/{{ item }}"
      as_single_query: "{{ postgresql_query_as_single_query }}"
    loop:
      - billy-create-tables.sql
      - billy-create-constraints.sql
      - billy-create-foreign-keys.sql
      - billy-create-indices.sql
      - billy-fill.sql
    when: installation_mode == "new"

  become: true
  become_user: postgres
