
- name: install upgrades as_single_query
  community.postgresql.postgresql_query:
    db: "{{ fworch_db_name }}"
    path_to_script: "{{ database_install_dir }}/upgrade/{{ item }}.sql"
    as_single_query: "{{ postgresql_query_as_single_query }}"
  loop: "{{ upgrade_files | sort }}"
  become: yes
  become_user: postgres
