---
- block:

    - name: add {{ billytest_user }} user
      user:
        name: "{{ billytest_user }}"
        shell: /bin/bash
        home: "{{ billytest_home }}"
        state: present
        group: "{{ billy_group }}"
        generate_ssh_key: true
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa     
        comment: "{{ product_name }} test user for webhook github integration"

    - name: give {{ billytest_user }} user full sudo access without pwd for webhook automation
      lineinfile:
        path: /etc/sudoers
        line: "{{ billytest_user }} ALL=(ALL) NOPASSWD:ALL"

    # ansible is needed for running auto install on the fwo host itself
    - name: Install packages for webhook receiver
      package:
        name: "{{ item }}"
      loop:
        - python3-flask
        - ansible
        
    - name: create webhook dir {{ billytest_home }}/webhook
      file:
        dest: "{{ billytest_home }}/webhook"
        state: directory
        owner: "{{ billytest_user }}"
        group: "{{ billy_group }}"
        mode: "0775"

    - name: copy startup file from template
      template:
        src: billy-webhook-receiver.service.j2
        dest: "/lib/systemd/system/billy-webhook-receiver.service"
        mode: "0755"
      notify: "restart daemons"

    - name: copy webhook file from template
      template:
        src: billy-webhook-receiver.py.j2
        dest: "{{ billytest_home }}/billy-webhook-receiver.py"
        mode: "0755"
      notify: "restart daemons"

    - name: make webhook run at host startup
      systemd:
        name: billy-webhook-receiver
        enabled: true

    - name: start webhook
      systemd:
        name: billy-webhook-receiver
        state: restarted

    - name: create webhook secret file
      lineinfile:
        path: "{{ billytest_home }}/billy-webhook.secret"
        line: "{{ webhook_secret }}"
        create: true
        backup: true
        mode: 0600
        owner: "{{ billytest_user }}"
        group: "{{ billy_group }}"

    - name: create billytest gitconfig file
      blockinfile:
        path: "{{ billytest_home }}/.gitconfig"
        block: |
          [http]
            proxy = {{ http_proxy }}
          [https]
            proxy = {{ http_proxy }}
        create: true
        backup: true
        mode: 0644
        owner: "{{ billytest_user }}"
        group: "{{ billy_group }}"

  become: true
