- name: rename old ldap manager pwd file in case of pre-5.7.1 upgrade 
  copy:
    src: "{{ billy_secrets_dir }}/ldap_manager_pw.txt"
    dest: "{{ ldap_manager_pwd_file }}"
    force: true
    remote_src: true
  become: true
  ignore_errors: true
