# database_dir: /var/lib/pgsql/data
postgresql_package: postgresql
postgresql_test_package: pgtap
postgresql_c_client_library_header_files: libpq-dev
postgresql_dev_package_prefix: postgresql-server-dev
postgresql_query_as_single_query: false
database_install_dir: "{{ billy_home }}/database"

database_users:
  - dbbackup

database_groups:
  - dbbackupusers
  - reporters
  - billyadmins

database_idempotent_files:
  - billy-basic-procs.sql
  - billy-report.sql
  - billy-views.sql
  - billy-api-funcs.sql
  - billy-grants.sql
  - billy-texts.sql
